/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "background": "#f8f9fa",
        "primary-container": "#135f67",
        "on-secondary-fixed-variant": "#354a53",
        "on-surface": "#191c1d",
        "surface-container": "#edeeef",
        "secondary-container": "#cfe6f2",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed": "#071e27",
        "surface-container-highest": "#e1e3e4",
        "on-tertiary-fixed-variant": "#6b3a16",
        "primary": "#00464d",
        "surface-container-low": "#f3f4f5",
        "secondary-fixed": "#cfe6f2",
        "secondary": "#4c616c",
        "primary-fixed": "#abeef7",
        "outline": "#6f7979",
        "on-error": "#ffffff",
        "tertiary": "#62330f",
        "secondary-fixed-dim": "#b4cad6",
        "surface": "#f8f9fa",
        "primary-fixed-dim": "#90d1da",
        "surface-tint": "#206770",
        "surface-container-high": "#e7e8e9",
        "on-tertiary-fixed": "#311300",
        "on-primary-fixed-variant": "#004f56",
        "on-primary-container": "#95d6df",
        "error-container": "#ffdad6",
        "surface-variant": "#e1e3e4",
        "inverse-on-surface": "#f0f1f2",
        "error": "#ba1a1a",
        "on-secondary": "#ffffff",
        "on-surface-variant": "#3f4949",
        "tertiary-container": "#7e4924",
        "on-background": "#191c1d",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#001f23",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#ffb688",
        "surface-bright": "#f8f9fa",
        "tertiary-fixed": "#ffdbc7",
        "inverse-primary": "#90d1da",
        "outline-variant": "#bec8c9",
        "on-error-container": "#93000a",
        "inverse-surface": "#2e3132",
        "on-secondary-container": "#526772",
        "surface-dim": "#d9dadb",
        "on-tertiary-container": "#ffbe95"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "9999px"
      },
      fontFamily: {
        "public-sans": ["Public Sans", "sans-serif"],
        "inter": ["Inter", "sans-serif"],
        "headline": ["Public Sans", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
